using System;
using System.Collections.Generic;
namespace CreatureMorph {
internal static class PrefabPaths {
internal static readonly Dictionary<string, string> Files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
    { "Crash", "Assets/AddressableResources/WorldEntities/Environment/Crash.prefab" },
    { "Floater", "Assets/AddressableResources/WorldEntities/Environment/Floater.prefab" },
    { "PrecursorDroid", "Assets/AddressableResources/WorldEntities/Creatures/Precursor_Droid.prefab" },
    { "SkyrayNonRoosting", "Assets/AddressableResources/WorldEntities/Creatures/Skyray.prefab" },
    { "Biter_02", "Assets/AddressableResources/WorldEntities/Creatures/Biter_02.prefab" },
    { "Biter", "Assets/AddressableResources/WorldEntities/Creatures/Biter.prefab" },
    { "BladderFish", "Assets/AddressableResources/WorldEntities/Creatures/BladderFish.prefab" },
    { "BladderFishSchool", "Assets/AddressableResources/WorldEntities/Creatures/BladderFishSchool.prefab" },
    { "Bleeder", "Assets/AddressableResources/WorldEntities/Creatures/Bleeder.prefab" },
    { "BoneShark", "Assets/AddressableResources/WorldEntities/Creatures/BoneShark.prefab" },
    { "Boomerang", "Assets/AddressableResources/WorldEntities/Creatures/Boomerang.prefab" },
    { "BoomerangFishSchool", "Assets/AddressableResources/WorldEntities/Creatures/BoomerangFishSchool.prefab" },
    { "BoomerangLava", "Assets/AddressableResources/WorldEntities/Creatures/BoomerangLava.prefab" },
    { "CaveCrawler_02", "Assets/AddressableResources/WorldEntities/Creatures/CaveCrawler_02.prefab" },
    { "CaveCrawler_03", "Assets/AddressableResources/WorldEntities/Creatures/CaveCrawler_03.prefab" },
    { "CaveCrawler", "Assets/AddressableResources/WorldEntities/Creatures/CaveCrawler.prefab" },
    { "CrabSnake", "Assets/AddressableResources/WorldEntities/Creatures/CrabSnake.prefab" },
    { "CrabSquid", "Assets/AddressableResources/WorldEntities/Creatures/CrabSquid.prefab" },
    { "CreatureRespawner", "Assets/AddressableResources/WorldEntities/Creatures/CreatureRespawner.prefab" },
    { "CuteFish", "Assets/AddressableResources/WorldEntities/Creatures/CuteFish.prefab" },
    { "Eyeye", "Assets/AddressableResources/WorldEntities/Creatures/Eyeye.prefab" },
    { "EyeyeLava", "Assets/AddressableResources/WorldEntities/Creatures/EyeyeLava.prefab" },
    { "GarryFish", "Assets/AddressableResources/WorldEntities/Creatures/GarryFish.prefab" },
    { "Gasopod", "Assets/AddressableResources/WorldEntities/Creatures/Gasopod.prefab" },
    { "GasPod", "Assets/AddressableResources/WorldEntities/Creatures/GasPod.prefab" },
    { "GhostLeviathan", "Assets/AddressableResources/WorldEntities/Creatures/GhostLeviathan.prefab" },
    { "GhostLeviathanJuvenile", "Assets/AddressableResources/WorldEntities/Creatures/GhostLeviathanJuvenile.prefab" },
    { "GhostRayBlue", "Assets/AddressableResources/WorldEntities/Creatures/GhostRayBlue.prefab" },
    { "GhostRayRed", "Assets/AddressableResources/WorldEntities/Creatures/GhostRayRed.prefab" },
    { "HoleFish", "Assets/AddressableResources/WorldEntities/Creatures/HoleFish.prefab" },
    { "HoleFishSchool", "Assets/AddressableResources/WorldEntities/Creatures/HoleFishSchool.prefab" },
    { "HoopFish_02_School", "Assets/AddressableResources/WorldEntities/Creatures/HoopFish_02_School.prefab" },
    { "HoopFish_02", "Assets/AddressableResources/WorldEntities/Creatures/HoopFish_02.prefab" },
    { "HoopFish", "Assets/AddressableResources/WorldEntities/Creatures/HoopFish.prefab" },
    { "HoopFishSchool", "Assets/AddressableResources/WorldEntities/Creatures/HoopFishSchool.prefab" },
    { "HoverFish", "Assets/AddressableResources/WorldEntities/Creatures/HoverFish.prefab" },
    { "JellyRay", "Assets/AddressableResources/WorldEntities/Creatures/JellyRay.prefab" },
    { "Jumper", "Assets/AddressableResources/WorldEntities/Creatures/Jumper.prefab" },
    { "JuvenileEmperorSpawner", "Assets/AddressableResources/WorldEntities/Creatures/JuvenileEmperorSpawner.prefab" },
    { "LavaLarva", "Assets/AddressableResources/WorldEntities/Creatures/LavaLarva.prefab" },
    { "LavaLizard", "Assets/AddressableResources/WorldEntities/Creatures/LavaLizard.prefab" },
    { "Mesmer", "Assets/AddressableResources/WorldEntities/Creatures/Mesmer.prefab" },
    { "Oculus", "Assets/AddressableResources/WorldEntities/Creatures/Oculus.prefab" },
    { "Peeper", "Assets/AddressableResources/WorldEntities/Creatures/Peeper.prefab" },
    { "Precursor_Droid", "Assets/AddressableResources/WorldEntities/Creatures/Precursor_Droid.prefab" },
    { "RabbitRay", "Assets/AddressableResources/WorldEntities/Creatures/RabbitRay.prefab" },
    { "ReaperLeviathan", "Assets/AddressableResources/WorldEntities/Creatures/ReaperLeviathan.prefab" },
    { "Reefback", "Assets/AddressableResources/WorldEntities/Creatures/Reefback.prefab" },
    { "ReefbackBaby", "Assets/AddressableResources/WorldEntities/Creatures/ReefbackBaby.prefab" },
    { "Reginald", "Assets/AddressableResources/WorldEntities/Creatures/Reginald.prefab" },
    { "RockGrub", "Assets/AddressableResources/WorldEntities/Creatures/RockGrub.prefab" },
    { "SandShark", "Assets/AddressableResources/WorldEntities/Creatures/SandShark.prefab" },
    { "SeaDragon", "Assets/AddressableResources/WorldEntities/Creatures/SeaDragon.prefab" },
    { "SeaEmperorBabiesSpawner", "Assets/AddressableResources/WorldEntities/Creatures/SeaEmperorBabiesSpawner.prefab" },
    { "SeaEmperorBaby", "Assets/AddressableResources/WorldEntities/Creatures/SeaEmperorBaby.prefab" },
    { "SeaEmperorJuvenile", "Assets/AddressableResources/WorldEntities/Creatures/SeaEmperorJuvenile.prefab" },
    { "SeaTreader", "Assets/AddressableResources/WorldEntities/Creatures/SeaTreader.prefab" },
    { "Shocker", "Assets/AddressableResources/WorldEntities/Creatures/Shocker.prefab" },
    { "Skyray", "Assets/AddressableResources/WorldEntities/Creatures/Skyray.prefab" },
    { "SpadeFish", "Assets/AddressableResources/WorldEntities/Creatures/SpadeFish.prefab" },
    { "SpineEel", "Assets/AddressableResources/WorldEntities/Creatures/SpineEel.prefab" },
    { "Stalker", "Assets/AddressableResources/WorldEntities/Creatures/Stalker.prefab" },
    { "BloodGrass", "Assets/AddressableResources/WorldEntities/Creatures/Unused/BloodGrass.prefab" },
    { "Grabcrab", "Assets/AddressableResources/WorldEntities/Creatures/Unused/Grabcrab.prefab" },
    { "GrabcrabHome", "Assets/AddressableResources/WorldEntities/Creatures/Unused/GrabcrabHome.prefab" },
    { "Grower", "Assets/AddressableResources/WorldEntities/Creatures/Unused/Grower.prefab" },
    { "HoleFishDummy", "Assets/AddressableResources/WorldEntities/Creatures/Unused/HoleFishDummy.prefab" },
    { "TestDrone", "Assets/AddressableResources/WorldEntities/Creatures/Unused/TestDrone.prefab" },
    { "Warper", "Assets/AddressableResources/WorldEntities/Creatures/Warper.prefab" },
    { "WarperSpawner", "Assets/AddressableResources/WorldEntities/Creatures/WarperSpawner.prefab" },
};
}}
